name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .[dev]
    - name: Pytest
      run: |
        pytest
    - name: Linters
      run: |
        pylint ariadne_codegen tests
        mypy ariadne_codegen --ignore-missing-imports
        # these test outputs represent things that may be committed into other projects that may
        # have strict mypy settings, and so they should be maximally annotated.
        mypy --strict tests/main/*/expected_client
        black --check .
        isort . --check-only
